// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package model

import (
	"context"
)

const createPreparation = `-- name: CreatePreparation :one
insert into preparations(accomplish) values(?) returning accomplish, important, complete, distractions, measurable, noteworthy
`

func (q *Queries) CreatePreparation(ctx context.Context, accomplish string) (Preparation, error) {
	row := q.db.QueryRowContext(ctx, createPreparation, accomplish)
	var i Preparation
	err := row.Scan(
		&i.Accomplish,
		&i.Important,
		&i.Complete,
		&i.Distractions,
		&i.Measurable,
		&i.Noteworthy,
	)
	return i, err
}
