// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"
)

type Cycle struct {
	ID           int64
	CreatedAt    time.Time
	SessionID    int64
	CycleTimerID int64
	Accomplish   string
	Started      string
	Hazards      string
	Energy       int64
	Morale       int64
	Target       int64
	Noteworthy   string
	Distractions string
	Improve      string
}

type Session struct {
	ID                int64
	CreatedAt         time.Time
	Status            string
	NumCycles         int64
	StartAt           time.Time
	StartCycleTimerID int64
	Accomplish        string
	Important         string
	Complete          string
	Distractions      string
	Measurable        string
	Noteworthy        string
	Target            int64
	Done              string
	Compare           string
	Bogged            string
	Replicate         string
	Takeaways         string
	Nextsteps         string
}
